version: "3.8"

services:
  db:
    image: postgres:16.1
    container_name: postgres
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=shareit
      - POSTGRES_USER=shareit
      - POSTGRES_PASSWORD=shareit
      - TZ=UTC
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -q -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 10

  server:
    build: ./server
    image: shareit-server
    container_name: shareit-server
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "9090:9090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shareit
      - SPRING_DATASOURCE_USERNAME=shareit
      - SPRING_DATASOURCE_PASSWORD=shareit
      - TZ=UTC
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:9090/actuator/health"]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 10s

  gateway:
    build: ./gateway
    image: shareit-gateway
    container_name: shareit-gateway
    depends_on:
      server:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      - SHAREIT_SERVER_URL=http://server:9090
      - TZ=UTC